name: CI
on:
  push: { branches: [main] }
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Build & test with coverage
        run: mvn -B -ntp clean verify

      - name: Enforce JaCoCo coverage >= 0.80
        run: |
          RATE=$(xmllint --xpath \
            "string(//counter[@type='INSTRUCTION']/@covered div (//counter[@type='INSTRUCTION']/@covered + //counter[@type='INSTRUCTION']/@missed))" \
            target/site/jacoco/jacoco.xml)
          python3 - <<'PY'
import os, sys
r=float(os.environ["RATE"])
print(f"Coverage={r:.2%}")
sys.exit(0 if r>=0.80 else 1)
PY
